### PR TITLE
Added Shadow shader and tilemap

### PR DESCRIPTION
**Pull request by ShahnawazHussain28**
the torch has some problems. it grows and shrinks. The angle comparison is messed up in the shadow.glsl

### CODE REVIEW

**Comment by ificiana** [comment]
@ShahnawazHussain28 please run pre-commit before pushing 
check https://pre-commit.com/

**Comment by ificiana** [comment]
> the torch has some problems. it grows and shrinks. The angle comparison is messed up in the shadow.glsl

alright noted, will look into it

**Comment by ificiana** [comment]
rest looks good to me, good work!

**Comment by VagishVela** [comment]
@ificiana commenting on https://github.com/ificiana/pyweek35/issues/8#issuecomment-1485011249 here.

I would think using non python might break the rules. 

I tried to convert it into python, let me know if you can get this to work:
```
import numpy as np
from PIL import Image

N = 100
FOV = 60

def terrain(texture, sample_point):
    sample_point_alpha = texture[sample_point].a
    sample_stepped = 1 if sample_point_alpha > 0.1 else 0
    return 1.0 - sample_stepped

def main_image(light_position, light_size, angle, i_channel0, i_channel1, resolution):
    frag_color = np.zeros((resolution[1], resolution[0], 4), dtype=np.float32)

    for y in range(resolution[1]):
        for x in range(resolution[0]):
            frag_coord = np.array([x, y], dtype=np.float32)
            distance_to_light = np.linalg.norm(light_position - frag_coord)
            normalized_frag_coord = frag_coord / resolution
            normalized_light_coord = light_position / resolution
            light_amount = 1.0
            dir = normalized_frag_coord - normalized_light_coord
            this_angle = np.arctan2(dir[1], dir[0])

            if this_angle < np.radians(angle - FOV/2) or this_angle > np.radians(angle + FOV/2):
                light_amount = 0.0
            else:
                for i in range(N):
                    t = i / N
                    sample_point = (normalized_frag_coord * (1 - t) + normalized_light_coord * t) * resolution
                    sample_point = np.clip(sample_point.astype(np.int), 0, np.array(resolution) - 1)
                    shadow_amount = terrain(i_channel0, tuple(sample_point))
                    light_amount *= shadow_amount

            light_amount *= 1.0 - np.clip((distance_to_light - light_size) / light_size, 0, 1)
            black_color = np.array([0.0, 0.0, 0.0, 1.0])
            frag_color[y, x] = black_color * (1 - light_amount) + i_channel1[tuple(normalized_frag_coord)] * light_amount

    return frag_color
```

# Example usage
```
light_position = np.array([200, 200], dtype=np.float32)
light_size = 100
angle = 30
i_channel0 = Image.open("path/to/texture0.png")  # Replace with the path to your texture0 image
i_channel1 = Image.open("path/to/texture1.png")  # Replace with the path to your texture1 image
resolution = np.array(i_channel0.size, dtype=np.int)

result = main_image(light_position, light_size, angle, i_channel0, i_channel1, resolution)
result_image = Image.fromarray((result * 255).astype(np.uint8), "RGBA")
result_image.show()  # Display the resulting image

```

**Review by ificiana — APPROVED** [review]
merging, but shaders are still a bit of a grey area

**Pull request merged**
